### ISSUE TITLE
iOS8 problem?

### ISSUE THREAD

**Issue by Queiron** [janumedia/AirPrintANE#3]
Dear Januartha,
Your AirPrinANE Adobe Air extension is not cooperating with the new Air versions (after 14) as it gives the following error: "Error: META-INF/ANE/iPhone-ARM/libproductStore.a are required to have universal iOS libraries. Please contact the ANE developer(s) to get the same."

I am wondering if you have any immediate plans for updating your extension as its the only way currently how we can include Air Print functionality in our iOS app.

**Comment by janumedia** [comment]
Hi, 
It seem related to 64 bit support. Prev version only support 64 bit
Please try ver 1.0.2. Let me know if fixed the issue. 
I don't have AIR 14 SDK or latest yet to test

**Comment by Queiron** [comment]
Hi,
Thanks for the swift response, I have been able to test your update. AIR 14 works with your extension but Apple doesn't accept it anymore, they accept only AIR 16 version an higher. Any chance you can get your hands on an AIR 16 SDK or have any idea to fix it? I can test if changes were effective or not.

**Comment by janumedia** [comment]
Hi,

I added new iOS library using iOS SDK 8.1 and ver 1.0.3 .ane built using AIR SDK 17.
Let me know if this update this issue

**Comment by caraiz** [comment]
Hi,
i have tried version 1.0.3 in iOS 8 but the problem still exists.
I had found similar issues in others frameworks, i send you some links, maybe it can help you to solve the problem.

https://github.com/katzer/cordova-plugin-printer/issues/43
https://github.com/katzer/cordova-plugin-printer/issues/26

Thanks

**Comment by Queiron** [comment]
Hi,
we have also tried and as caraiz noted, the problem is still there.

**Comment by caraiz** [comment]
Hi,

we've gotten it to work with the following code:

if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad)
{
UIWindow *window = [[UIApplication sharedApplication] keyWindow];
UIView *view = window.rootViewController.view;
[printerController presentFromRect:CGRectMake(10, 10, 0, 0) inView:view animated:YES completionHandler:completionHandler];
}
else
{
[printerController presentAnimated:YES completionHandler:completionHandler];
}

Tested in iOS 7, 8.2 and 8.3.

The screen position is fixed at 10, 10, but will be fine that in the future the "printBitmapData" method admits a custom position (Point) and/or the align in screen (top_left, top_center, ...).

**Comment by Queiron** [comment]
Dear  Januartha,

Can you try to update the code with the one caraiz suggested? Our programmer could not find the place to insert the code piece caraiz suggested.

Thanks

**Comment by janumedia** [comment]
@Queiron @caraiz please check latest committed (version 1.1.0). 
I add posX and posY (default value = 10) for iPad only because I think this issue only on iPad

here the complete usage:
airPrintAne.printBitmapData (bitmapData, AirPrintANE.PRINT_OUT_DOCUMENT, AirPrintANE.PRINT_ORIENT_PORTRAIT, posX, posY);

**Comment by Queiron** [comment]
@janumedia Thanks for all the help, tested on iPad and iPhone as well, working perfectly. Im gonna close the issue, cheers
