### ISSUE TITLE
Crash on iOS 8.3 and AIR 22

### ISSUE THREAD

**Issue by wilkuintheair** [janumedia/AirPrintANE#4]
Hi,
I have problems with your extension when using AIR 22 beta on iOS 8.3 iPad.
From what I've noticed the problem is when you try to add the dialog to the view:
```
UIViewController *rootViewController = [[[UIApplication sharedApplication] keyWindow] rootViewController];

[printerController presentFromRect:CGRectMake(posX, posY, 0, 0) inView:rootViewController.view animated:YES completionHandler:completionHandler];
```

This code is crashing only on one of my devices. It works fine on iOS 7.1.1, 8.1 and 9.3.
Also it works fine on all devices when using AIR 21.

I'm not sure if I should address this issue to you or directly to the Adobe team but maybe you can figure something out.

Regards,
Piotr Wilk

**Comment by janumedia** [comment]
Probably  because still bugs in AIR 22 beta version. Sorry I don't have device with iOS 8.3 for now.
But I will investigate it. Thank for this report

**Comment by wilkuintheair** [comment]
Yep, it's AIR 22 beta issue, fixed in the newest beta release.
