### ISSUE TITLE
Cancel Event not captured

### ISSUE THREAD

**Issue by kptac** [janumedia/AirPrintANE#5]
We really need to register events here - especially the "Cancel" Button one. Currently we cant be sure if the user actually printed the document or pressed Cancel.

Please see if this can be done. Great job otherwise.

Thanks

**Comment by janumedia** [comment]
Actually that just simple update AirPrintANE.m line 119 - 125 with this

`// print error
            if (!completed && error) {
                NSString *errorStr = [NSString stringWithFormat:@"Failed! due to error in domain %@ with error code %lu ", error.domain, (long)error.code];
                FREDispatchStatusEventAsync(context, (uint8_t*)[event_print_error UTF8String], (uint8_t*) (uint8_t*)[errorStr UTF8String]);
            // print completed
            } else if(completed)
            {
                NSString *successStr = [NSString stringWithFormat:@"Success!"];
                FREDispatchStatusEventAsync(context, (uint8_t*)[event_print_complete UTF8String], (uint8_t*) (uint8_t*)[successStr UTF8String]);
            // print canceled
            } else
            {
                NSString *successStr = [NSString stringWithFormat:@"Canceled!"];
                FREDispatchStatusEventAsync(context, (uint8_t*)[event_print_canceled UTF8String], (uint8_t*) (uint8_t*)[successStr UTF8String]);
            }`

And dont forget to define
`NSString * event_print_canceled = @"print_canceled";`

**Comment by janumedia** [comment]
some update with AS3 class will also needed to 'print_canceled' event

**Comment by janumedia** [comment]
please refer to version 1.1.1 with cancelation status event
